# Generated by Django 5.0.6 on 2024-06-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_app", "0002_remove_administrator_db_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance_db",
            name="event_date",
            field=models.TimeField(auto_now="True"),
            preserve_default="True",
        ),
        migrations.AlterField(
            model_name="grievance_db",
            name="G_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="grievance_db",
            name="files",
            field=models.FileField(default=None, upload_to="G_media/"),
        ),
    ]
