# Generated by Django 5.0 on 2024-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0003_grievance_db_event_date_alter_grievance_db_g_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance_db',
            name='statue',
            field=models.CharField(max_length=5),
        ),
    ]
