# Generated by Django 5.0 on 2024-06-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0004_alter_grievance_db_statue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance_db',
            old_name='statue',
            new_name='status',
        ),
    ]
