# Generated by Django 5.0 on 2024-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0005_rename_statue_grievance_db_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance_db',
            name='severity',
            field=models.CharField(max_length=30),
        ),
    ]
