# Generated by Django 5.0 on 2024-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0006_alter_grievance_db_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance_db',
            name='files',
            field=models.FileField(blank=True, default=None, upload_to='G_media/'),
        ),
    ]
